{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "apc-web.fullname" . }}
  labels:
    {{- include "apc-web.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "apc-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
